server:
  port: 8080
  servlet:
    context-path: /luminate

spring:
  # 数据库相关配置
  datasource:
    username: root
    password: mysqlcxr
    url: jdbc:mysql://localhost:3306/luminate
    driver-class-name: com.mysql.cj.jdbc.Driver
  # kafka 相关配置
  kafka:
    bootstrap-servers: 192.168.20.160:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 1000
      enable-auto-commit: true
      auto-offset-reset: earliest
  # redis 相关配置
  redis:
    host: 192.168.20.160
    port: 6379
    password: CXr123456_redis
    database: 2


# kafka topic name
luminate:
  topic:
    name: luminate
# 阿里云 SMS 相关配置
aliyun:
  sms:
    account:
      access-key-id: LTAI5tNRKzZv8Z73vMsEUwvq
      access-key-secret: CwqIKAnKWeGEafi8Rc4ezBDKVuyVU8
      sign-name: luminate
      template-code: SMS_276225334
# qq email 相关配置
email:
  host: smtp.qq.com
  port: 465
  user: warrior22@qq.com
  from: warrior22@qq.com
  pass: mszicvbchqzwbfii

xxl:
  job:
    admin:
      addresses: 192.168.20.160:6767/xxl-job-admin/ # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      username: admin # 后台用户名
      password: 123456 # 后台密码
    executor:
      appname: luminate # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      ip: # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 6666 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath:  # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
    accessToken:  # 执行器通讯TOKEN [选填]：非空时启用；
