server:
  port: 8080
  servlet:
    context-path: /luminate

spring:
  datasource:
    username: root
    password: mysqlcxr
    url: jdbc:mysql://localhost:3306/luminate
    driver-class-name: com.mysql.cj.jdbc.Driver