server:
  port: 8080
  servlet:
    context-path: /luminate

spring:
  # 数据库相关配置
  datasource:
    username: root
    password: mysqlcxr
    url: jdbc:mysql://localhost:3306/luminate
    driver-class-name: com.mysql.cj.jdbc.Driver
  # kafka 相关配置
  kafka:
    bootstrap-servers: 192.168.20.160:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 1000
      enable-auto-commit: true
      auto-offset-reset: earliest
  # redis 相关配置
  redis:
    host: 192.168.20.160
    port: 6379
    password: CXr123456_redis
    database: 2


# kafka topic name
luminate:
  topic:
    name: luminate
# 阿里云 SMS 相关配置
aliyun:
  sms:
    account:
      access-key-id: LTAI5tNRKzZv8Z73vMsEUwvq
      access-key-secret: CwqIKAnKWeGEafi8Rc4ezBDKVuyVU8
      sign-name: luminate
      template-code: SMS_276225334
# qq email 相关配置
email:
  host: smtp.qq.com
  port: 465
  user: warrior22@qq.com
  from: warrior22@qq.com
  pass: mszicvbchqzwbfii

xxl:
  job:
    admin:
      addresses: http://localhost:8081/xxl-job-admin
      username: admin
      password: 123456
    executor:
      appname: luminate-executor
      ip: 127.0.0.1
      port: -1
      logpath:
      logretentiondays: 30
    accessToken:
